### PR TITLE
Load array scripts synchronously

### PR DESCRIPTION
**Pull request by nguyenhuylinhdev**
Hi, this PR add function **loadScriptSync** to replace function **replaceAndRunScript**

Because when use replaceAndRunScript, script load not synchronous, so sometime it show error because other script not loaded

- Use function **replaceAndRunScript**:

Screenshot_2

- Use function **loadScriptSync**:

Screenshot_3

### CODE REVIEW

**Comment by prowebat** [comment]
I'm experiencing the same issue with the scripts.
This pull request works, but the disadvantage is, that each script is loaded sequentially, which makes the page somewhat slower if you have many scripts.

Possible solutions I found:
* (not quite elegant): loading all scripts with an xhr and then putting the content directly into a script-tag. this also makes debugging hard.
* fire a custom "flamethrower:page:loaded" event after the html is updated. and the scripts should listen to this event and only then execute it's code.

**Comment by nguyenhuylinhdev** [comment]
Hi @prowebat, I found [loadJS](https://github.com/filamentgroup/loadJS) and and realize that just add **async=false**, it work like a charm!
So I will close this PR and create new PR tomorrow.

- Use function **replaceAndRunScript**:


Screenshot_2

Screenshot_1

**Comment by prowebat** [comment]
nice, that worked.
and i also found out that you can just set it in the html with async="" (empty value)

hint for the new PR:
"newScript.async = false" should be before line 113 (so attributes can overwrite the default false value).

**Comment by nguyenhuylinhdev** [comment]
Yeah, set **async=""** in html is worked but I have a problem: 
- At index.html, if I click to about => it worked (all script in about.html will be load synchronously)
- At about.html, if I click refresh on browser => sometime it not worked, because scripts load asynchronously.

[link test](https://resonant-placid-allspice.glitch.me/)
[source code](https://glitch.com/edit/#!/resonant-placid-allspice?path=index.html)

Screenshot_1


I will continue test it.

**Pull request closed without merging**
