### PR TITLE
:bug: Fixes head dom diffing

### PR DESCRIPTION
**Pull request by ekwoka**
Solves: https://github.com/fireship-io/flamethrower/issues/45

I had introduced a bug not caught on the tests (in https://github.com/fireship-io/flamethrower/pull/28 ) that this fixes. It was preventing the loop from running and correctly identifying fresh/stale nodes beyond the first few while not otherwise sacrificing performance.

Also implements a simple short circuit on the lookbacks in the event old nodes or new nodes are undefined.

### CODE REVIEW

**Comment by shreyassanthu77** [comment]
This still doesn't work, new head nodes are being added but the old nodes are no being removed
image

**Comment by ekwoka** [comment]
@shreyassanthu77 Are you sure?

https://user-images.githubusercontent.com/43540491/186188308-187a2828-6878-446a-aaff-fe34c7d49c34.mov

**Comment by shreyassanthu77** [comment]
> @shreyassanthu77 Are you sure?
> 
>  Screen.Recording.2022-08-23.at.6.43.37.PM.mov

I am pretty sure, as you can see in the screenshot the title and some of style tags keeps re-adding

**Comment by shreyassanthu77** [comment]
this is my setup:
image
image
used esbuild to build the package
image
and this is the result
https://user-images.githubusercontent.com/58223424/186193507-917132cd-5b05-4b49-8d6a-712c211f1f69.mp4

**Comment by shreyassanthu77** [comment]
> @shreyassanthu77 oh that makes more sense.
> 
> This change is not on my main branch (the one you're using). That would explain the difference in behaviors.

Ok that makes sense. I'm really sorry for wasting your time, I should've checked that. Sorry again and thank you :)

**Comment by shreyassanthu77** [comment]
Finally, it works absolutely fine, thank you man

**Pull request merged**
