### PR TITLE
Feat: Adding prefetch on hover

### PR DESCRIPTION
**Pull request by b0iq**
I suggest adding prefetch on hover only which is optimize the library for large page with a lot of links.

### CODE REVIEW

**Comment by Tropix126** [comment]
Hmmm, just an idea. Would it be more future-proof to add a property such as `{ prefetchBehavior: "hover" }` rather than a boolean in this case? Might mitigate the amount of config options in the future if more prefetch options end up being added.

**Comment by b0iq** [comment]
@Tropix126 Great!, I was thinking about that too, but I don't want my PR looks dirty with a lot of new features such as enums...etc. So for know I think it is good enough. Or if it was so important from now I can continue developing it once some reviewer tell me his opinion 😄

**Comment by codediodeio** [comment]
Good idea, thanks! I'd prefer `{ prefetch: "hover" }` since it would make no sense to use both hover and intersection at the same time. The interface could look like `prefetch?: 'visible' | 'hover'`.

**Comment by ekwoka** [comment]
An option seems nice.

Since then the api could support something like an options for maybe I want visible but only links of a certain kind (main links), not necessarily all links.

**Comment by b0iq** [comment]
@codediodeio Done 🔥

**Comment by b0iq** [comment]
@ekwoka Cool, do you me we should achieve that by add an attribute to certain elements that is requiring prefetching such as:
 ```<a href="/about" prefetch >About</a>```?

**Comment by ekwoka** [comment]
@b0iq Yeah, something like that.

probably more like `data-prefetch` but even have it configurable.

**Pull request merged**
